log:
  level: level(10)
  processing: plain # or json
  output_file: # falls back to stdout if no file is provided
  permanent_attributes:
    - env: dev
    - app_name: example

transaction:
  recorder: apm # or dummy
