log:
  level: info
  processing: plain # or json
  output_file: # falls back to stdout if no file is provided
  permanent_attributes:
    - env: test
    - app_name: example

transaction:
  recorder: apm # or dummy
